name: Release Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # LINUX BUILD
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

    # cache deps
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: dependencies
        key: ${{ runner.os }}-deps-${{ hashFiles('.github/workflows/release.yml') }}

    # fetch if cache miss
    - name: Fetch Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        mkdir -p dependencies
        git clone https://github.com/luau-lang/luau.git dependencies/luau
        git clone https://github.com/raysan5/raylib.git dependencies/raylib
        git clone https://github.com/ocornut/imgui.git dependencies/imgui
        git clone https://github.com/raylib-extras/rlImGui.git dependencies/rlImGui

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release -j$(nproc)

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BlockEngine-Linux
        path: build/BlockEngine

  # WINDOWS BUILD
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # cache deps
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: dependencies
        key: ${{ runner.os }}-deps-${{ hashFiles('.github/workflows/release.yml') }}

    # fetch if cache miss
    - name: Fetch Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p dependencies
        git clone https://github.com/luau-lang/luau.git dependencies/luau
        git clone https://github.com/raysan5/raylib.git dependencies/raylib
        git clone https://github.com/ocornut/imgui.git dependencies/imgui
        git clone https://github.com/raylib-extras/rlImGui.git dependencies/rlImGui

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release -j4

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BlockEngine-Windows
        path: build/Release/BlockEngine.exe